version: "3"

services:
  product-db:
    container_name: product-api
    image: postgres
    environment:
      POSTGRES_PASSWORD: goproduct
    ports:
      - "5432:5432"
    restart: always

  server:
    container_name: product-api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - product-db
    env_file:
      - .env
